DEMO_DEXTEROUS_HAND = {
    'as_of': '2026-07-24',
    'evidence': [
        {
            'company': '灵心巧手',
            'event_type': 'factory_or_capacity',
            'phase': 'build_organize',
            'event_date': '2026-05-25',
            'title': '灵心巧手加速硬科技落地，2026年月产能将超过4000台',
            'snippet': '企业披露从技术突破走向规模化量产，2025年完成多轮融资，资金用于研发、技能库、产能扩建与供应链优化。',
            'source_url': 'https://www.jjckb.cn/20260525/ea97394681b748acbb5adf9dc10a961d/c.html',
            'source_name': '经济参考报',
            'source_grade': 'B',
            'people': ['周永', '左家平'],
            'organizations': ['红杉中国', '蚂蚁集团', '中金资本'],
        },
        {
            'company': '灵心巧手',
            'event_type': 'factory_or_capacity',
            'phase': 'strategy_capital',
            'event_date': '2026-03-12',
            'title': '德清灵巧手超级工厂开启量产新篇章',
            'snippet': '德清超级工厂支撑2026年5万至10万台年度交付目标，融资继续用于产品迭代、产能扩充和全栈能力建设。',
            'source_url': 'https://dqnews.zjol.com.cn/dqnews/system/2026/03/12/035171905.shtml',
            'source_name': '德清新闻网',
            'source_grade': 'A',
            'organizations': ['德清县产业发展投资基金'],
        },
        {
            'company': '灵心巧手',
            'event_type': 'funding',
            'phase': 'strategy_capital',
            'event_date': '2025-11-25',
            'title': '灵心巧手完成数亿元A+轮融资',
            'snippet': '公司计划在下一年度交付5万至10万台灵巧手，融资对应产品迭代、生态与规模交付。',
            'source_url': 'https://www.cnfin.com/gs-lb/detail/20251125/4340555_1.html',
            'source_name': '新华财经',
            'source_grade': 'B',
            'organizations': ['浙江省创新投资集团', '德清县产业发展投资基金', '乐聚机器人'],
        },
        {
            'company': '因时机器人',
            'event_type': 'factory_or_capacity',
            'phase': 'strategy_capital',
            'event_date': '2026-06-05',
            'title': '公开披露文件列示因时机器人2026年扩产计划',
            'snippet': '披露材料称2025年灵巧手交付突破1万台，2026年目标3万至5万台，并推动常熟工厂建设投产。',
            'source_url': 'https://pdf.dfcfw.com/pdf/H2_AN202606051823288012_1.pdf',
            'source_name': '上市公司公开披露文件镜像',
            'source_grade': 'B',
        },
        {
            'company': '因时机器人',
            'event_type': 'major_order',
            'phase': 'build_organize',
            'event_date': '2026-03-20',
            'title': '宇树科技公开披露因时机器人为灵巧手供应商',
            'snippet': '交易所披露文件确认宇树科技外购灵巧手的主要供应商包括因时机器人，形成头部客户交付验证。',
            'source_url': 'https://static.sse.com.cn/stock/disclosure/announcement/c/202603/002178_20260320_OE27.pdf',
            'source_name': '上海证券交易所公开披露',
            'source_grade': 'A',
            'organizations': ['宇树科技'],
        },
        {
            'company': '因时机器人',
            'event_type': 'funding',
            'phase': 'strategy_capital',
            'event_date': '2025-04-29',
            'title': '因时机器人完成近亿元B3轮融资',
            'snippet': '神骐资本领投；华盖资本投资人评价其商业化、海外增长和头部客户矩阵，资金窗口与扩张需求相互印证。',
            'source_url': 'https://news.pedaily.cn/202504/549066.shtml',
            'source_name': '投资界',
            'source_grade': 'B',
            'people': ['王少鲲'],
            'organizations': ['神骐资本', '华盖资本科技产业基金'],
        },
        {
            'company': '戴盟机器人',
            'event_type': 'funding',
            'phase': 'strategy_capital',
            'event_date': '2026-06-04',
            'title': '戴盟机器人完成亿元A轮融资',
            'snippet': '汇川产投与中国电信联合投资，资金用于物理交互数据集、物理世界模型和商业化能力建设。',
            'source_url': 'https://news.pedaily.cn/202606/564853.shtml',
            'source_name': '投资界',
            'source_grade': 'B',
            'organizations': ['汇川产投', '中国电信'],
        },
        {
            'company': '戴盟机器人',
            'event_type': 'partnership',
            'phase': 'build_organize',
            'event_date': '2025-02-13',
            'title': '戴盟与联想签订战略合作协议',
            'snippet': '双方依托联想智能制造中小试基地推进视触觉传感器和五指灵巧手产业化，官方活动披露了投资与制造协同负责人。',
            'source_url': 'https://www.dmrobot.com/news/19.html',
            'source_name': '戴盟机器人官网',
            'source_grade': 'A',
            'people': ['段江哗', '林林', '梁颖'],
            'organizations': ['联想创投', '联想南方智能制造基地'],
        },
        {
            'company': '戴盟机器人',
            'event_type': 'data_or_model',
            'phase': 'build_organize',
            'event_date': '2024-11-18',
            'title': '戴盟连续完成两轮亿元级天使+融资',
            'snippet': '资金和产业资源用于超大规模物理交互数据集、模型研发及真实场景商业闭环，团队孵化自港科大机器人研究院。',
            'source_url': 'https://capital.lenovo.com/news/detail/id/1045/s/1.html',
            'source_name': '联想创投',
            'source_grade': 'A',
            'people': ['段江哗', '王煜'],
            'organizations': ['香港科技大学机器人研究院', '联想创投', '国中资本', '金鼎资本'],
        },
    ],
    'routes': {
        '灵心巧手': [
            {
                'kind': 'investor',
                'target': '红杉中国、蚂蚁集团、中金资本',
                'path': '先在 Michael Page CRM 中查找这三家机构的已合作投资团队或其机器人被投企业联系人，请投资方引荐创始人周永或组织负责人。',
                'evidence_url': 'https://www.cls.cn/detail/2109076',
                'grade': 'B',
                'note': '公开融资报道列明投资机构及资金用途。',
            },
            {
                'kind': 'alumni',
                'target': '周永—华中科技大学少年班',
                'path': '在 Michael Page 顾问、客户和候选人网络中查找华中科技大学校友，优先选择机器人、精密制造或创业投资领域校友请求暖介绍。',
                'evidence_url': 'https://www.cls.cn/detail/2361737',
                'grade': 'B',
                'note': '公开人物报道披露周永的教育背景。',
            },
            {
                'kind': 'former_colleague',
                'target': '左家平—达闼机器人、九号机器人',
                'path': '检索 Michael Page 既有人才库中曾与左家平同期任职达闼或九号的总监以上候选人，请共同前同事作专业引荐。',
                'evidence_url': 'https://www.cls.cn/detail/2361737',
                'grade': 'B',
                'note': '公开人物报道披露其曾在达闼机器人、九号机器人担任技术负责人。',
            },
        ],
        '因时机器人': [
            {
                'kind': 'named_investor',
                'target': '王少鲲—华盖资本科技产业基金',
                'path': '优先由 Michael Page 与华盖资本或其智能制造被投企业的现有关系，联系公开代表本轮投资观点的王少鲲，请其引荐因时创始团队。',
                'evidence_url': 'https://news.pedaily.cn/202504/549066.shtml',
                'grade': 'B',
                'note': '融资报道明确引用华盖资本科技产业基金副总裁王少鲲。',
            },
            {
                'kind': 'lead_investor',
                'target': '神骐资本',
                'path': '查找神骐资本机器人或先进制造投资团队及共同被投企业创始人，围绕常熟工厂管理团队搭建请求引荐。',
                'evidence_url': 'https://news.pedaily.cn/202504/549066.shtml',
                'grade': 'B',
                'note': '公开融资报道列明神骐资本为B3轮领投方。',
            },
            {
                'kind': 'alumni_network',
                'target': '北航机器人研究所、北京科技大学机器人团队',
                'path': '从 Michael Page 现有人才库筛选北航/北科大机器人团队校友及前研究人员，人工核对与因时创始团队的实际重合后再请求引荐。',
                'evidence_url': 'https://pdf.dfcfw.com/pdf/H3_AP202410021640138987_1.pdf',
                'grade': 'B',
                'note': '公开行业材料描述创始团队来源；需二次核对具体届别和共同经历。',
            },
        ],
        '戴盟机器人': [
            {
                'kind': 'named_investor',
                'target': '林林、梁颖—联想创投',
                'path': '通过 Michael Page 与联想集团/联想创投的现有客户关系，优先联系公开出席戴盟合作活动的林林或梁颖，请其引荐段江哗。',
                'evidence_url': 'https://www.dmrobot.com/news/19.html',
                'grade': 'A',
                'note': '戴盟官网列明联想创投合伙人林林、董事总经理梁颖出席合作活动。',
            },
            {
                'kind': 'academic_mentor',
                'target': '段江哗—王煜—香港科技大学机器人研究院',
                'path': '从港科大机器人研究院校友、王煜教授产业合作网络或 Michael Page 香港科技客户关系切入，先验证共同关系，再请求师门暖介绍。',
                'evidence_url': 'https://capital.lenovo.com/news/detail/id/1045/s/1.html',
                'grade': 'A',
                'note': '投资方官网确认公司由王煜教授与段江哗博士联合创立并孵化于港科大。',
            },
            {
                'kind': 'current_investor',
                'target': '汇川产投、中国电信',
                'path': '优先查找 Michael Page 工业自动化与通信行业顾问对汇川技术、中国电信投资或战略部门的现有关系，以数据平台主管或算法研发总监组织搭建为议题请求引荐。',
                'evidence_url': 'https://news.pedaily.cn/202606/564853.shtml',
                'grade': 'B',
                'note': '2026年A轮融资报道列明两家联合投资方。',
            },
        ],
    },
    'ad_checks': {
        '灵心巧手': {
            'checked_at': '2026-07-24',
            'queries': ['灵心巧手 量产总监 制造运营总监 供应链总监 招聘'],
            'matching_results': 0,
            'other_director_ads': ['机器人产品工业设计总监'],
        },
        '因时机器人': {
            'checked_at': '2026-07-24',
            'queries': ['因时机器人 常熟工厂总经理 制造运营总监 供应链总监 招聘'],
            'matching_results': 0,
            'other_director_ads': ['KA总监'],
        },
        '戴盟机器人': {
            'checked_at': '2026-07-24',
            'queries': ['戴盟机器人 具身数据平台主管 机器人算法总监 招聘'],
            'matching_results': 0,
            'other_director_ads': ['商业拓展经理/总监'],
        },
    },
}
